/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.stats.getLicenseStats.Response.Raw,
    CodecombatApi.LicenseStatsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).LicenseStatsResponse);

export declare namespace Response {
    type Raw = serializers.LicenseStatsResponse.Raw;
}
