/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.stats.getPlaytimeStats.Response.Raw,
    CodecombatApi.PlaytimeStatsResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).PlaytimeStatsResponse);

export declare namespace Response {
    type Raw = serializers.PlaytimeStatsResponse.Raw;
}
