/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LicenseStatsResponse {
    licenseDaysGranted?: number;
    licenseDaysUsed?: number;
    licenseDaysRemaining?: number;
    activeLicenses?: number;
}
