/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const AddOauth2IdentityRequest: core.serialization.Schema<
    serializers.AddOauth2IdentityRequest.Raw,
    CodeCombatApi.AddOauth2IdentityRequest
> = core.serialization.object({
    provider: core.serialization.string(),
    accessToken: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
});

export declare namespace AddOauth2IdentityRequest {
    interface Raw {
        provider: string;
        accessToken?: string | null;
        code?: string | null;
    }
}
