/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const AddOAuthIdentityRequest: core.serialization.Schema<
    serializers.AddOAuthIdentityRequest.Raw,
    CodeCombat.AddOAuthIdentityRequest
> = core.serialization.object({
    provider: core.serialization.string(),
    accessToken: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
});

export declare namespace AddOAuthIdentityRequest {
    interface Raw {
        provider: string;
        accessToken?: string | null;
        code?: string | null;
    }
}
