/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const CreateUserRequest: core.serialization.Schema<
    serializers.CreateUserRequest.Raw,
    CodeCombat.CreateUserRequest
> = core.serialization.object({
    name: core.serialization.string(),
    email: core.serialization.string(),
    role: core.serialization.lazy(async () => (await import("../../../..")).UserRole).optional(),
    preferredLanguage: core.serialization.string().optional(),
    heroConfig: core.serialization.lazyObject(async () => (await import("../../../..")).HeroConfig).optional(),
    birthday: core.serialization.string().optional(),
});

export declare namespace CreateUserRequest {
    interface Raw {
        name: string;
        email: string;
        role?: serializers.UserRole.Raw | null;
        preferredLanguage?: string | null;
        heroConfig?: serializers.HeroConfig.Raw | null;
        birthday?: string | null;
    }
}
