/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const GetHeroRequest: core.serialization.Schema<serializers.GetHeroRequest.Raw, CodeCombat.GetHeroRequest> =
    core.serialization.object({
        thangType: core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString).optional(),
    });

export declare namespace GetHeroRequest {
    interface Raw {
        thangType?: serializers.ObjectIdString.Raw | null;
    }
}
