/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const ModifyUserRequest: core.serialization.Schema<
    serializers.ModifyUserRequest.Raw,
    CodeCombatApi.ModifyUserRequest
> = core.serialization.object({
    name: core.serialization.string(),
    birthday: core.serialization.string().optional(),
});

export declare namespace ModifyUserRequest {
    interface Raw {
        name: string;
        birthday?: string | null;
    }
}
