/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const SetAceConfigRequest: core.serialization.Schema<
    serializers.SetAceConfigRequest.Raw,
    CodeCombatApi.SetAceConfigRequest
> = core.serialization.object({
    liveCompletion: core.serialization.boolean().optional(),
    behaviors: core.serialization.boolean().optional(),
    language: core.serialization.string().optional(),
});

export declare namespace SetAceConfigRequest {
    interface Raw {
        liveCompletion?: boolean | null;
        behaviors?: boolean | null;
        language?: string | null;
    }
}
