/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const SetAceConfig: core.serialization.Schema<serializers.SetAceConfig.Raw, CodeCombat.SetAceConfig> =
    core.serialization.object({
        liveCompletion: core.serialization.boolean().optional(),
        behaviors: core.serialization.boolean().optional(),
        language: core.serialization.string().optional(),
    });

export declare namespace SetAceConfig {
    interface Raw {
        liveCompletion?: boolean | null;
        behaviors?: boolean | null;
        language?: string | null;
    }
}
