/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const ShortenSubscriptionRequest: core.serialization.Schema<
    serializers.ShortenSubscriptionRequest.Raw,
    CodeCombat.ShortenSubscriptionRequest
> = core.serialization.object({
    ends: core.serialization.date(),
});

export declare namespace ShortenSubscriptionRequest {
    interface Raw {
        ends: string;
    }
}
