/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const UsersUpdateRequest: core.serialization.Schema<
    serializers.UsersUpdateRequest.Raw,
    CodeCombat.UsersUpdateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    birthday: core.serialization.string().optional(),
});

export declare namespace UsersUpdateRequest {
    interface Raw {
        name: string;
        birthday?: string | null;
    }
}
