/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const UsersCreateRequest: core.serialization.Schema<
    serializers.UsersCreateRequest.Raw,
    CodeCombat.UsersCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    email: core.serialization.string(),
    role: core.serialization.lazy(async () => (await import("../../../..")).UsersCreateRequestRole).optional(),
    preferredLanguage: core.serialization.string().optional(),
    heroConfig: core.serialization
        .lazyObject(async () => (await import("../../../..")).UsersCreateRequestHeroConfig)
        .optional(),
    birthday: core.serialization.string().optional(),
});

export declare namespace UsersCreateRequest {
    interface Raw {
        name: string;
        email: string;
        role?: serializers.UsersCreateRequestRole.Raw | null;
        preferredLanguage?: string | null;
        heroConfig?: serializers.UsersCreateRequestHeroConfig.Raw | null;
        birthday?: string | null;
    }
}
