/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const UsersSetHeroRequest: core.serialization.Schema<
    serializers.UsersSetHeroRequest.Raw,
    CodeCombat.UsersSetHeroRequest
> = core.serialization.object({
    thangType: core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString).optional(),
});

export declare namespace UsersSetHeroRequest {
    interface Raw {
        thangType?: serializers.ObjectIdString.Raw | null;
    }
}
