/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const UsersGrantLicenseRequest: core.serialization.Schema<
    serializers.UsersGrantLicenseRequest.Raw,
    CodeCombat.UsersGrantLicenseRequest
> = core.serialization.object({
    ends: core.serialization.lazy(async () => (await import("../../../..")).DatetimeString),
});

export declare namespace UsersGrantLicenseRequest {
    interface Raw {
        ends: serializers.DatetimeString.Raw;
    }
}
