/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const UsersSetAceConfigRequest: core.serialization.Schema<
    serializers.UsersSetAceConfigRequest.Raw,
    CodeCombat.UsersSetAceConfigRequest
> = core.serialization.object({
    liveCompletion: core.serialization.boolean().optional(),
    behaviors: core.serialization.boolean().optional(),
    language: core.serialization.string().optional(),
});

export declare namespace UsersSetAceConfigRequest {
    interface Raw {
        liveCompletion?: boolean | null;
        behaviors?: boolean | null;
        language?: string | null;
    }
}
