/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const AceConfig: core.serialization.ObjectSchema<serializers.AceConfig.Raw, CodeCombat.AceConfig> =
    core.serialization.object({
        language: core.serialization.string().optional(),
    });

export declare namespace AceConfig {
    interface Raw {
        language?: string | null;
    }
}
