/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const ClassroomStatsInfo: core.serialization.ObjectSchema<
    serializers.ClassroomStatsInfo.Raw,
    CodecombatApi.ClassroomStatsInfo
> = core.serialization.object({
    gamesCompleted: core.serialization.number().optional(),
    playtime: core.serialization.number().optional(),
});

export declare namespace ClassroomStatsInfo {
    interface Raw {
        gamesCompleted?: number | null;
        playtime?: number | null;
    }
}
