/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const LevelSessionResponse: core.serialization.ObjectSchema<
    serializers.LevelSessionResponse.Raw,
    CodeCombatApi.LevelSessionResponse
> = core.serialization.object({
    state: core.serialization.lazyObject(async () => (await import("../../..")).LevelSessionState),
    level: core.serialization.lazyObject(async () => (await import("../../..")).LevelSessionLevelInfo),
    levelId: core.serialization.property("levelID", core.serialization.string()),
    creator: core.serialization.lazy(async () => (await import("../../..")).ObjectId),
    playtime: core.serialization.number(),
    changed: core.serialization.lazy(async () => (await import("../../..")).Datetime),
    created: core.serialization.lazy(async () => (await import("../../..")).Datetime),
    dateFirstCompleted: core.serialization.lazy(async () => (await import("../../..")).Datetime),
    submitted: core.serialization.boolean(),
    published: core.serialization.boolean(),
});

export declare namespace LevelSessionResponse {
    interface Raw {
        state: serializers.LevelSessionState.Raw;
        level: serializers.LevelSessionLevelInfo.Raw;
        levelID: string;
        creator: serializers.ObjectId.Raw;
        playtime: number;
        changed: serializers.Datetime.Raw;
        created: serializers.Datetime.Raw;
        dateFirstCompleted: serializers.Datetime.Raw;
        submitted: boolean;
        published: boolean;
    }
}
