/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const LevelSessionLevelInfo: core.serialization.ObjectSchema<
    serializers.LevelSessionLevelInfo.Raw,
    CodeCombatApi.LevelSessionLevelInfo
> = core.serialization.object({
    original: core.serialization.string(),
});

export declare namespace LevelSessionLevelInfo {
    interface Raw {
        original: string;
    }
}
