/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Level: core.serialization.ObjectSchema<serializers.Level.Raw, CodeCombat.Level> =
    core.serialization.object({
        original: core.serialization.string().optional(),
    });

export declare namespace Level {
    interface Raw {
        original?: string | null;
    }
}
