/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const PlayStats: core.serialization.ObjectSchema<serializers.PlayStats.Raw, CodeCombat.PlayStats> =
    core.serialization.object({
        gamesCompleted: core.serialization.number().optional(),
        playtime: core.serialization.number().optional(),
    });

export declare namespace PlayStats {
    interface Raw {
        gamesCompleted?: number | null;
        playtime?: number | null;
    }
}
