/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.users.addOauth2Identity.Request.Raw,
    CodeCombatApi.AddOauth2IdentityRequest
> = core.serialization.object({
    provider: core.serialization.string(),
    accessToken: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
});

export declare namespace Request {
    interface Raw {
        provider: string;
        accessToken?: string | null;
        code?: string | null;
    }
}

export const Response: core.serialization.Schema<
    serializers.users.addOauth2Identity.Response.Raw,
    CodeCombatApi.UserResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).UserResponse);

export declare namespace Response {
    type Raw = serializers.UserResponse.Raw;
}
