/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.users.setAceConfig.Request.Raw,
    CodeCombatApi.SetAceConfigRequest
> = core.serialization.object({
    liveCompletion: core.serialization.boolean().optional(),
    behaviors: core.serialization.boolean().optional(),
    language: core.serialization.string().optional(),
});

export declare namespace Request {
    interface Raw {
        liveCompletion?: boolean | null;
        behaviors?: boolean | null;
        language?: string | null;
    }
}

export const Response: core.serialization.Schema<
    serializers.users.setAceConfig.Response.Raw,
    CodeCombatApi.UserResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).UserResponse);

export declare namespace Response {
    type Raw = serializers.UserResponse.Raw;
}
