/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.users.setHero.Request.Raw, CodeCombatApi.SetHeroRequest> =
    core.serialization.object({
        thangType: core.serialization.lazy(async () => (await import("../../..")).ObjectId).optional(),
    });

export declare namespace Request {
    interface Raw {
        thangType?: serializers.ObjectId.Raw | null;
    }
}

export const Response: core.serialization.Schema<serializers.users.setHero.Response.Raw, CodeCombatApi.UserResponse> =
    core.serialization.lazyObject(async () => (await import("../../..")).UserResponse);

export declare namespace Response {
    type Raw = serializers.UserResponse.Raw;
}
