/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CodecombatApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CodecombatApiTimeoutError.prototype);
    }
}
