/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class CodeCombatTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, CodeCombatTimeoutError.prototype);
    }
}
