/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClanResponse {
    id?: CodeCombat.ObjectIdString;
    name?: string;
    displayName?: string;
    members?: CodeCombat.ObjectIdString[];
    ownerId?: CodeCombat.ObjectIdString;
    description?: string;
    type?: string;
    kind?: string;
    metadata?: Record<string, unknown>;
}
