/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClanResponse {
    id?: CodeCombatApi.ObjectId;
    name?: string;
    displayName?: string;
    members?: CodeCombatApi.ObjectId[];
    ownerId?: CodeCombatApi.ObjectId;
    description?: string;
    type?: string;
    kind?: string;
}
