/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClanResponse {
    id?: CodecombatApi.ObjectId;
    name?: string;
    displayName?: string;
    members?: CodecombatApi.ObjectId[];
    ownerId?: CodecombatApi.ObjectId;
    description?: string;
    type?: string;
    kind?: string;
}
