/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as CodeCombat from "../../../api";
import * as core from "../../../core";

export const PostUsersHandleOAuthIdentitiesRequest: core.serialization.Schema<
    serializers.PostUsersHandleOAuthIdentitiesRequest.Raw,
    CodeCombat.PostUsersHandleOAuthIdentitiesRequest
> = core.serialization.object({
    provider: core.serialization.string(),
    accessToken: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
});

export declare namespace PostUsersHandleOAuthIdentitiesRequest {
    interface Raw {
        provider: string;
        accessToken?: string | null;
        code?: string | null;
    }
}
