/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const ClanRequest: core.serialization.Schema<serializers.ClanRequest.Raw, CodeCombatApi.ClanRequest> =
    core.serialization.object({
        userId: core.serialization.string(),
    });

export declare namespace ClanRequest {
    interface Raw {
        userId: string;
    }
}
