/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const UpsertClanRequest: core.serialization.Schema<
    serializers.UpsertClanRequest.Raw,
    CodeCombat.UpsertClanRequest
> = core.serialization.object({
    userId: core.serialization.string(),
});

export declare namespace UpsertClanRequest {
    interface Raw {
        userId: string;
    }
}
