/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A `"student"` or `"teacher"`. If unset, a home user will be created, unable to join classrooms.
 */
export type UserRole = "student" | "teacher";

export const UserRole = {
    Student: "student",
    Teacher: "teacher",
} as const;
