/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClansUpsertMemberRequest {
    /** The `_id` or `slug` of the user to add to the clan. */
    userId: string;
}
