/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClassroomsCreateRequestAceConfig {
    /** Programming language for the classroom */
    language?: string;
}
