/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "..";

/**
 * Subset of properties listed here
 */
export interface ClassroomResponseWithCode {
    id?: CodeCombat.ObjectIdString;
    name?: string;
    members?: CodeCombat.ObjectIdString[];
    ownerId?: CodeCombat.ObjectIdString;
    description?: string;
    code?: string;
    codeCamel?: string;
    courses?: CodeCombat.ClassroomResponseWithCodeCoursesItem[];
    clanId?: CodeCombat.ObjectIdString;
}
