/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "..";

/**
 * Subset of properties listed here
 */
export interface ClassroomResponse {
    id?: CodeCombat.ObjectIdString;
    name?: string;
    members?: CodeCombat.ObjectIdString[];
    ownerId?: CodeCombat.ObjectIdString;
    description?: string;
    courses?: CodeCombat.ClassroomResponseCoursesItem[];
}
