/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClassroomsGetMembersStatsResponseItemStats {
    gamesCompleted?: number;
    /** Total play time in seconds */
    playtime?: number;
}
