/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "..";

export interface LevelSessionResponse {
    state?: CodeCombat.LevelSessionResponseState;
    level?: CodeCombat.LevelSessionResponseLevel;
    /** Level slug like `wakka-maul` */
    levelId?: string;
    creator?: CodeCombat.ObjectIdString;
    /** Time played in seconds. */
    playtime?: number;
    changed?: CodeCombat.DatetimeString;
    created?: CodeCombat.DatetimeString;
    dateFirstCompleted?: CodeCombat.DatetimeString;
    /** For arenas. Whether or not the level has been added to the ladder. */
    submitted?: boolean;
    /** For shareable projects. Whether or not the project has been shared with classmates. */
    published?: boolean;
}
