/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LicenseStatsResponse {
    /** Total number of license days granted */
    licenseDaysGranted?: number;
    /** Number of license days used */
    licenseDaysUsed?: number;
    /** Number of license days remaining */
    licenseDaysRemaining?: number;
    /** Number of active/valid licenses */
    activeLicenses?: number;
}
