/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "..";

/**
 * Subset of properties listed here
 */
export interface UserResponse {
    id?: CodeCombat.ObjectIdString;
    email?: string;
    name?: string;
    slug?: string;
    role?: CodeCombat.RoleString;
    stats?: CodeCombat.UserResponseStats;
    oAuthIdentities?: CodeCombat.UserResponseOAuthIdentitiesItem[];
    subscription?: CodeCombat.UserResponseSubscription;
    license?: CodeCombat.UserResponseLicense;
}
