/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.classrooms.getLevelsPlayedForUser.Response.Raw,
    CodeCombatApi.LevelSessionResponse[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).LevelSessionResponse));

export declare namespace Response {
    type Raw = serializers.LevelSessionResponse.Raw[];
}
