/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as CodeCombat from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.classrooms.getLevelsPlayed.Response.Raw,
    CodeCombat.LevelSessionResponse[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).LevelSessionResponse));

export declare namespace Response {
    type Raw = serializers.LevelSessionResponse.Raw[];
}
