/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.classrooms.getStats.Response.Raw,
    CodecombatApi.ClassroomStats[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ClassroomStats));

export declare namespace Response {
    type Raw = serializers.ClassroomStats.Raw[];
}
