/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.classrooms.removeUser.Request.Raw,
    Omit<CodecombatApi.RemoveUserRequest, "handle">
> = core.serialization.object({
    userId: core.serialization.string(),
    retMemberLimit: core.serialization.number().optional(),
});

export declare namespace Request {
    interface Raw {
        userId: string;
        retMemberLimit?: number | null;
    }
}

export const Response: core.serialization.Schema<
    serializers.classrooms.removeUser.Response.Raw,
    CodecombatApi.ClassroomResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).ClassroomResponse);

export declare namespace Response {
    type Raw = serializers.ClassroomResponse.Raw;
}
