/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClassroomsGetRequest {
    /**
     * The classroom's `code`.
     */
    code: string;
    /**
     * limit the return number of members for the classroom
     */
    retMemberLimit?: number;
}
