/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ClassroomsUpsertMemberRequest {
    /** The code for joining this classroom */
    code: string;
    /** The `_id` or `slug` of the user to add to the class. */
    userId: string;
    /** limit the return number of members for the classroom, the default value is 1000 */
    retMemberLimit?: number;
}
