/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

export interface CreateClassroomRequest {
    name: string;
    ownerId: CodeCombatApi.ObjectId;
    aceConfig: CodeCombatApi.AceConfig;
}
