/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

export interface CreateClassroomRequest {
    /** Name of the classroom */
    name: string;
    ownerId: CodeCombat.ObjectIdString;
    aceConfig: CodeCombat.AceConfig;
}
