/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetLevelsPlayedForUserRequest {
    /**
     * The classroom's `_id`.
     */
    classroomHandle: string;
    /**
     * The classroom member's `_id`.
     */
    memberHandle: string;
}
