/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface UnenrollUserRequest {
    /**
     * The classroom's `_id`.
     */
    classroomHandle: string;
    /**
     * The course's `_id`.
     */
    courseHandle: string;
    userId: CodecombatApi.ObjectId;
}
