/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const ClassroomResponseWithCodeCoursesItem: core.serialization.ObjectSchema<
    serializers.ClassroomResponseWithCodeCoursesItem.Raw,
    CodeCombat.ClassroomResponseWithCodeCoursesItem
> = core.serialization.object({
    id: core.serialization.property(
        "_id",
        core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional()
    ),
    levels: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
    enrolled: core.serialization
        .list(core.serialization.lazy(async () => (await import("..")).ObjectIdString))
        .optional(),
    instanceId: core.serialization.property(
        "instance_id",
        core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional()
    ),
});

export declare namespace ClassroomResponseWithCodeCoursesItem {
    interface Raw {
        _id?: serializers.ObjectIdString.Raw | null;
        levels?: Record<string, unknown>[] | null;
        enrolled?: serializers.ObjectIdString.Raw[] | null;
        instance_id?: serializers.ObjectIdString.Raw | null;
    }
}
