/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const ClassroomResponseWithCode: core.serialization.ObjectSchema<
    serializers.ClassroomResponseWithCode.Raw,
    CodeCombat.ClassroomResponseWithCode
> = core.serialization.object({
    id: core.serialization.property(
        "_id",
        core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional()
    ),
    name: core.serialization.string().optional(),
    members: core.serialization
        .list(core.serialization.lazy(async () => (await import("..")).ObjectIdString))
        .optional(),
    ownerId: core.serialization.property(
        "ownerID",
        core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional()
    ),
    description: core.serialization.string().optional(),
    code: core.serialization.string().optional(),
    codeCamel: core.serialization.string().optional(),
    courses: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).ClassroomResponseWithCodeCoursesItem))
        .optional(),
    clanId: core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional(),
});

export declare namespace ClassroomResponseWithCode {
    interface Raw {
        _id?: serializers.ObjectIdString.Raw | null;
        name?: string | null;
        members?: serializers.ObjectIdString.Raw[] | null;
        ownerID?: serializers.ObjectIdString.Raw | null;
        description?: string | null;
        code?: string | null;
        codeCamel?: string | null;
        courses?: serializers.ClassroomResponseWithCodeCoursesItem.Raw[] | null;
        clanId?: serializers.ObjectIdString.Raw | null;
    }
}
