/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const ClassroomsCreateRequestAceConfig: core.serialization.ObjectSchema<
    serializers.ClassroomsCreateRequestAceConfig.Raw,
    CodeCombat.ClassroomsCreateRequestAceConfig
> = core.serialization.object({
    language: core.serialization.string().optional(),
});

export declare namespace ClassroomsCreateRequestAceConfig {
    interface Raw {
        language?: string | null;
    }
}
