/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const ClassroomsGetMembersStatsResponseItemStats: core.serialization.ObjectSchema<
    serializers.ClassroomsGetMembersStatsResponseItemStats.Raw,
    CodeCombat.ClassroomsGetMembersStatsResponseItemStats
> = core.serialization.object({
    gamesCompleted: core.serialization.number().optional(),
    playtime: core.serialization.number().optional(),
});

export declare namespace ClassroomsGetMembersStatsResponseItemStats {
    interface Raw {
        gamesCompleted?: number | null;
        playtime?: number | null;
    }
}
