/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const ClassroomsGetMembersStatsResponseItem: core.serialization.ObjectSchema<
    serializers.ClassroomsGetMembersStatsResponseItem.Raw,
    CodeCombat.ClassroomsGetMembersStatsResponseItem
> = core.serialization.object({
    id: core.serialization.property(
        "_id",
        core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional()
    ),
    stats: core.serialization
        .lazyObject(async () => (await import("..")).ClassroomsGetMembersStatsResponseItemStats)
        .optional(),
});

export declare namespace ClassroomsGetMembersStatsResponseItem {
    interface Raw {
        _id?: serializers.ObjectIdString.Raw | null;
        stats?: serializers.ClassroomsGetMembersStatsResponseItemStats.Raw | null;
    }
}
