/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const LevelSessionResponseLevel: core.serialization.ObjectSchema<
    serializers.LevelSessionResponseLevel.Raw,
    CodeCombat.LevelSessionResponseLevel
> = core.serialization.object({
    original: core.serialization.string().optional(),
});

export declare namespace LevelSessionResponseLevel {
    interface Raw {
        original?: string | null;
    }
}
