/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const LevelSessionResponse: core.serialization.ObjectSchema<
    serializers.LevelSessionResponse.Raw,
    CodeCombat.LevelSessionResponse
> = core.serialization.object({
    state: core.serialization.lazyObject(async () => (await import("..")).LevelSessionResponseState).optional(),
    level: core.serialization.lazyObject(async () => (await import("..")).LevelSessionResponseLevel).optional(),
    levelId: core.serialization.property("levelID", core.serialization.string().optional()),
    creator: core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional(),
    playtime: core.serialization.number().optional(),
    changed: core.serialization.lazy(async () => (await import("..")).DatetimeString).optional(),
    created: core.serialization.lazy(async () => (await import("..")).DatetimeString).optional(),
    dateFirstCompleted: core.serialization.lazy(async () => (await import("..")).DatetimeString).optional(),
    submitted: core.serialization.boolean().optional(),
    published: core.serialization.boolean().optional(),
});

export declare namespace LevelSessionResponse {
    interface Raw {
        state?: serializers.LevelSessionResponseState.Raw | null;
        level?: serializers.LevelSessionResponseLevel.Raw | null;
        levelID?: string | null;
        creator?: serializers.ObjectIdString.Raw | null;
        playtime?: number | null;
        changed?: serializers.DatetimeString.Raw | null;
        created?: serializers.DatetimeString.Raw | null;
        dateFirstCompleted?: serializers.DatetimeString.Raw | null;
        submitted?: boolean | null;
        published?: boolean | null;
    }
}
