/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const LicenseStatsResponse: core.serialization.ObjectSchema<
    serializers.LicenseStatsResponse.Raw,
    CodeCombat.LicenseStatsResponse
> = core.serialization.object({
    licenseDaysGranted: core.serialization.number().optional(),
    licenseDaysUsed: core.serialization.number().optional(),
    licenseDaysRemaining: core.serialization.number().optional(),
    activeLicenses: core.serialization.number().optional(),
});

export declare namespace LicenseStatsResponse {
    interface Raw {
        licenseDaysGranted?: number | null;
        licenseDaysUsed?: number | null;
        licenseDaysRemaining?: number | null;
        activeLicenses?: number | null;
    }
}
