/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const UsersCreateRequestRole: core.serialization.Schema<
    serializers.UsersCreateRequestRole.Raw,
    CodeCombat.UsersCreateRequestRole
> = core.serialization.enum_(["student", "teacher"]);

export declare namespace UsersCreateRequestRole {
    type Raw = "student" | "teacher";
}
