/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const UserResponseStats: core.serialization.ObjectSchema<
    serializers.UserResponseStats.Raw,
    CodeCombat.UserResponseStats
> = core.serialization.object({
    gamesCompleted: core.serialization.number().optional(),
    concepts: core.serialization.record(core.serialization.string(), core.serialization.number()).optional(),
    playTime: core.serialization.number().optional(),
});

export declare namespace UserResponseStats {
    interface Raw {
        gamesCompleted?: number | null;
        concepts?: Record<string, number> | null;
        playTime?: number | null;
    }
}
