/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const UserResponseSubscription: core.serialization.ObjectSchema<
    serializers.UserResponseSubscription.Raw,
    CodeCombat.UserResponseSubscription
> = core.serialization.object({
    ends: core.serialization.lazy(async () => (await import("..")).DatetimeString).optional(),
    active: core.serialization.boolean().optional(),
});

export declare namespace UserResponseSubscription {
    interface Raw {
        ends?: serializers.DatetimeString.Raw | null;
        active?: boolean | null;
    }
}
