/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as CodeCombat from "../../api";
import * as core from "../../core";

export const UsersCreateRequestHeroConfig: core.serialization.ObjectSchema<
    serializers.UsersCreateRequestHeroConfig.Raw,
    CodeCombat.UsersCreateRequestHeroConfig
> = core.serialization.object({
    thangType: core.serialization.lazy(async () => (await import("..")).ObjectIdString).optional(),
});

export declare namespace UsersCreateRequestHeroConfig {
    interface Raw {
        thangType?: serializers.ObjectIdString.Raw | null;
    }
}
