/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

export interface ClassroomStats {
    id?: CodeCombatApi.ObjectId;
    stats?: CodeCombatApi.ClassroomStatsInfo;
}
