/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface ClassroomStats {
    id?: CodecombatApi.ObjectId;
    stats?: CodecombatApi.ClassroomStatsInfo;
}
