/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClassroomResponseWithCode {
    id?: CodeCombatApi.ObjectId;
    name?: string;
    members?: CodeCombatApi.ObjectId[];
    ownerId?: CodeCombatApi.ObjectId;
    description?: string;
    code?: string;
    codeCamel?: string;
    courses?: CodeCombatApi.Course[];
    clanId?: CodeCombatApi.ObjectId;
}
