/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClassroomResponseWithCode {
    id?: CodecombatApi.ObjectId;
    name?: string;
    members?: CodecombatApi.ObjectId[];
    ownerId?: CodecombatApi.ObjectId;
    description?: string;
    code?: string;
    codeCamel?: string;
    courses?: CodecombatApi.Course[];
    clanId?: CodecombatApi.ObjectId;
}
