/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface LevelSessionResponse {
    state: CodecombatApi.LevelSessionState;
    level: CodecombatApi.LevelSessionLevelInfo;
    /** Level slug like `wakka-maul` */
    levelId: string;
    creator: CodecombatApi.ObjectId;
    /** Time played in seconds. */
    playtime: number;
    changed: CodecombatApi.Datetime;
    created: CodecombatApi.Datetime;
    dateFirstCompleted: CodecombatApi.Datetime;
    /** For arenas. Whether or not the level has been added to the ladder. */
    submitted: boolean;
    /** For shareable projects. Whether or not the project has been shared with classmates. */
    published: boolean;
}
