/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

export interface LevelSessionResponse {
    state: CodeCombatApi.LevelSessionState;
    level: CodeCombatApi.LevelSessionLevelInfo;
    /** Level slug like `wakka-maul` */
    levelId: string;
    creator: CodeCombatApi.ObjectId;
    /** Time played in seconds. */
    playtime: number;
    changed: CodeCombatApi.Datetime;
    created: CodeCombatApi.Datetime;
    dateFirstCompleted: CodeCombatApi.Datetime;
    /** For arenas. Whether or not the level has been added to the ladder. */
    submitted: boolean;
    /** For shareable projects. Whether or not the project has been shared with classmates. */
    published: boolean;
}
