/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const ClassroomsRemoveMemberRequest: core.serialization.Schema<
    serializers.ClassroomsRemoveMemberRequest.Raw,
    CodeCombat.ClassroomsRemoveMemberRequest
> = core.serialization.object({
    userId: core.serialization.string(),
    retMemberLimit: core.serialization.number().optional(),
});

export declare namespace ClassroomsRemoveMemberRequest {
    interface Raw {
        userId: string;
        retMemberLimit?: number | null;
    }
}
