/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const ClassroomsUpsertMemberRequest: core.serialization.Schema<
    serializers.ClassroomsUpsertMemberRequest.Raw,
    CodeCombat.ClassroomsUpsertMemberRequest
> = core.serialization.object({
    code: core.serialization.string(),
    userId: core.serialization.string(),
    retMemberLimit: core.serialization.number().optional(),
});

export declare namespace ClassroomsUpsertMemberRequest {
    interface Raw {
        code: string;
        userId: string;
        retMemberLimit?: number | null;
    }
}
