/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const ClassroomsCreateRequest: core.serialization.Schema<
    serializers.ClassroomsCreateRequest.Raw,
    CodeCombat.ClassroomsCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    ownerId: core.serialization.property(
        "ownerID",
        core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString)
    ),
    aceConfig: core.serialization.lazyObject(
        async () => (await import("../../../..")).ClassroomsCreateRequestAceConfig
    ),
});

export declare namespace ClassroomsCreateRequest {
    interface Raw {
        name: string;
        ownerID: serializers.ObjectIdString.Raw;
        aceConfig: serializers.ClassroomsCreateRequestAceConfig.Raw;
    }
}
