/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as CodeCombat from "../../../../../api";
import * as core from "../../../../../core";

export const ClassroomsRemoveEnrolledUserRequest: core.serialization.Schema<
    serializers.ClassroomsRemoveEnrolledUserRequest.Raw,
    Omit<CodeCombat.ClassroomsRemoveEnrolledUserRequest, "retMemberLimit">
> = core.serialization.object({
    userId: core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString),
});

export declare namespace ClassroomsRemoveEnrolledUserRequest {
    interface Raw {
        userId: serializers.ObjectIdString.Raw;
    }
}
