/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const CreateClassroomRequest: core.serialization.Schema<
    serializers.CreateClassroomRequest.Raw,
    CodeCombat.CreateClassroomRequest
> = core.serialization.object({
    name: core.serialization.string(),
    ownerId: core.serialization.property(
        "ownerID",
        core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString)
    ),
    aceConfig: core.serialization.lazyObject(async () => (await import("../../../..")).AceConfig),
});

export declare namespace CreateClassroomRequest {
    interface Raw {
        name: string;
        ownerID: serializers.ObjectIdString.Raw;
        aceConfig: serializers.AceConfig.Raw;
    }
}
