/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const DeleteUserFromClassroomRequest: core.serialization.Schema<
    serializers.DeleteUserFromClassroomRequest.Raw,
    CodeCombat.DeleteUserFromClassroomRequest
> = core.serialization.object({
    userId: core.serialization.string(),
    retMemberLimit: core.serialization.number().optional(),
});

export declare namespace DeleteUserFromClassroomRequest {
    interface Raw {
        userId: string;
        retMemberLimit?: number | null;
    }
}
