/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const EnrollUserInCourseRequest: core.serialization.Schema<
    serializers.EnrollUserInCourseRequest.Raw,
    Omit<CodeCombat.EnrollUserInCourseRequest, "retMemberLimit">
> = core.serialization.object({
    userId: core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString),
});

export declare namespace EnrollUserInCourseRequest {
    interface Raw {
        userId: serializers.ObjectIdString.Raw;
    }
}
