/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const EnrollUserRequest: core.serialization.Schema<
    serializers.EnrollUserRequest.Raw,
    Omit<CodeCombatApi.EnrollUserRequest, "retMemberLimit">
> = core.serialization.object({
    userId: core.serialization.lazy(async () => (await import("../../../..")).ObjectId),
});

export declare namespace EnrollUserRequest {
    interface Raw {
        userId: serializers.ObjectId.Raw;
    }
}
