/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const RemoveUserRequest: core.serialization.Schema<
    serializers.RemoveUserRequest.Raw,
    CodeCombatApi.RemoveUserRequest
> = core.serialization.object({
    userId: core.serialization.string(),
    retMemberLimit: core.serialization.number().optional(),
});

export declare namespace RemoveUserRequest {
    interface Raw {
        userId: string;
        retMemberLimit?: number | null;
    }
}
