/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const RemoveUserFromClassroomRequest: core.serialization.Schema<
    serializers.RemoveUserFromClassroomRequest.Raw,
    Omit<CodeCombat.RemoveUserFromClassroomRequest, "retMemberLimit">
> = core.serialization.object({
    userId: core.serialization.lazy(async () => (await import("../../../..")).ObjectIdString),
});

export declare namespace RemoveUserFromClassroomRequest {
    interface Raw {
        userId: serializers.ObjectIdString.Raw;
    }
}
