/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../../core";

export const UnenrollUserRequest: core.serialization.Schema<
    serializers.UnenrollUserRequest.Raw,
    Omit<CodeCombatApi.UnenrollUserRequest, "retMemberLimit">
> = core.serialization.object({
    userId: core.serialization.lazy(async () => (await import("../../../..")).ObjectId),
});

export declare namespace UnenrollUserRequest {
    interface Raw {
        userId: serializers.ObjectId.Raw;
    }
}
