/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { CodeCombatApi } from "@fern-api/codecombat";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Client {
    interface Options {
        environment?: environments.CodeCombatApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    /**
     * Returns the playtime stats
     */
    public async getPlaytimeStats(
        request?: CodeCombatApi.GetPlaytimeStatsRequest
    ): Promise<CodeCombatApi.PlaytimeStatsResponse> {
        const _queryParams = new URLSearchParams();
        if (request?.startDate != null) {
            _queryParams.append("startDate", request?.startDate);
        }

        if (request?.endDate != null) {
            _queryParams.append("endDate", request?.endDate);
        }

        if (request?.country != null) {
            _queryParams.append("country", request?.country);
        }

        const _response = await core.fetcher({
            url: urlJoin(
                this.options.environment ?? environments.CodeCombatApiEnvironment.Production,
                "playtime-stats"
            ),
            method: "GET",
            headers: {
                Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.credentials)),
            },
            queryParameters: _queryParams,
        });
        if (_response.ok) {
            return await serializers.stats.getPlaytimeStats.Response.parse(
                _response.body as serializers.stats.getPlaytimeStats.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CodeCombatApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CodeCombatApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CodeCombatApiTimeoutError();
            case "unknown":
                throw new errors.CodeCombatApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Returns the license stats
     */
    public async getLicenseStats(): Promise<CodeCombatApi.LicenseStatsResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment ?? environments.CodeCombatApiEnvironment.Production, "license-stats"),
            method: "GET",
            headers: {
                Authorization: core.BasicAuth.toAuthorizationHeader(await core.Supplier.get(this.options.credentials)),
            },
        });
        if (_response.ok) {
            return await serializers.stats.getLicenseStats.Response.parse(
                _response.body as serializers.stats.getLicenseStats.Response.Raw
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CodeCombatApiError({
                statusCode: _response.error.statusCode,
                responseBody: _response.error.rawBody,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CodeCombatApiError({
                    statusCode: _response.error.statusCode,
                    responseBody: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.CodeCombatApiTimeoutError();
            case "unknown":
                throw new errors.CodeCombatApiError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
