/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const UserRole: core.serialization.Schema<serializers.UserRole.Raw, CodeCombat.UserRole> =
    core.serialization.enum_(["student", "teacher"]);

export declare namespace UserRole {
    type Raw = "student" | "teacher";
}
