/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.clans.put.Request.Raw, CodeCombatApi.ClanRequest> =
    core.serialization.object({
        userId: core.serialization.string(),
    });

export declare namespace Request {
    interface Raw {
        userId: string;
    }
}

export const Response: core.serialization.Schema<serializers.clans.put.Response.Raw, CodeCombatApi.ClanResponse> =
    core.serialization.lazyObject(async () => (await import("../../..")).ClanResponse);

export declare namespace Response {
    type Raw = serializers.ClanResponse.Raw;
}
