/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface ClassroomResponse {
    id?: CodeCombat.ObjectIdString;
    /** The name of the classroom */
    name?: string;
    /** List of _ids of the student members of the classroom */
    members?: CodeCombat.ObjectIdString[];
    /** The _id of the teacher owner of the classroom. */
    ownerId?: CodeCombat.ObjectIdString;
    description?: string;
    courses?: CodeCombat.Course[];
}
