/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

export interface Course {
    id?: CodeCombat.ObjectIdString;
    levels?: Record<string, unknown>[];
    enrolled?: CodeCombat.ObjectIdString[];
    instanceId?: CodeCombat.ObjectIdString;
}
