/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

export interface Course {
    id?: CodeCombatApi.ObjectId;
    levels?: unknown[];
    enrolled?: CodeCombatApi.ObjectId[];
    instanceId?: CodeCombatApi.ObjectId;
}
