/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface Course {
    id?: CodecombatApi.ObjectId;
    levels?: unknown[];
    enrolled?: CodecombatApi.ObjectId[];
    instanceId?: CodecombatApi.ObjectId;
}
