/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

export interface License {
    ends?: CodeCombatApi.Datetime;
    active?: boolean;
}
