/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

export interface Subscription {
    ends?: CodeCombat.DatetimeString;
    active?: boolean;
}
