/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface UserResponse {
    id?: CodeCombat.ObjectIdString;
    email?: string;
    name?: string;
    slug?: string;
    role?: CodeCombat.RoleString;
    stats?: CodeCombat.UserStats;
    oAuthIdentities?: CodeCombat.AuthIdentity[];
    subscription?: CodeCombat.Subscription;
    license?: CodeCombat.License;
}
