/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface UserResponse {
    id?: CodecombatApi.ObjectId;
    email?: string;
    name?: string;
    slug?: string;
    role?: CodecombatApi.RoleString;
    stats?: CodecombatApi.UserStats;
    oAuthIdentities?: CodecombatApi.OauthIdentity[];
    subscription?: CodecombatApi.Subscription;
    license?: CodecombatApi.License;
}
