/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UserStats {
    gamesCompleted?: number;
    concepts?: Record<string, number>;
    /** Included only when specifically requested on the endpoint */
    playTime?: number;
}
