/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombatApi } from "@fern-api/codecombat";

/**
 * Subset of properties listed here
 */
export interface UserResponse {
    id?: CodeCombatApi.ObjectId;
    email?: string;
    name?: string;
    slug?: string;
    role?: CodeCombatApi.RoleString;
    stats?: CodeCombatApi.UserStats;
    oAuthIdentities?: CodeCombatApi.OauthIdentity[];
    subscription?: CodeCombatApi.Subscription;
    license?: CodeCombatApi.License;
}
