/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as AuthClient } from "./api/resources/auth/client/Client";
import { Client as ClansClient } from "./api/resources/clans/client/Client";
import { Client as ClassroomsClient } from "./api/resources/classrooms/client/Client";
import { Client as StatsClient } from "./api/resources/stats/client/Client";
import { Client as UsersClient } from "./api/resources/users/client/Client";

export declare namespace CodeCombatApiClient {
    interface Options {
        environment?: environments.CodeCombatApiEnvironment | string;
        credentials?: core.Supplier<core.BasicAuth>;
    }
}

export class CodeCombatApiClient {
    constructor(private readonly options: CodeCombatApiClient.Options) {}

    #auth: AuthClient | undefined;

    public get auth(): AuthClient {
        return (this.#auth ??= new AuthClient(this.options));
    }

    #clans: ClansClient | undefined;

    public get clans(): ClansClient {
        return (this.#clans ??= new ClansClient(this.options));
    }

    #classrooms: ClassroomsClient | undefined;

    public get classrooms(): ClassroomsClient {
        return (this.#classrooms ??= new ClassroomsClient(this.options));
    }

    #stats: StatsClient | undefined;

    public get stats(): StatsClient {
        return (this.#stats ??= new StatsClient(this.options));
    }

    #users: UsersClient | undefined;

    public get users(): UsersClient {
        return (this.#users ??= new UsersClient(this.options));
    }
}
