/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CodeCombatEnvironment = {
    Production: "https://codecombat.com/api",
} as const;

export type CodeCombatEnvironment = typeof CodeCombatEnvironment.Production;
