/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CodecombatApiEnvironment = {
    Production: "https://codecombat.com/api",
} as const;

export type CodecombatApiEnvironment = typeof CodecombatApiEnvironment.Production;
