/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AddOauth2IdentityRequest {
    /**
     * The document's `_id` or `slug`.
     */
    handle: string;
    provider: string;
    accessToken?: string;
    code?: string;
}
