/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface CreateUserRequest {
    name: string;
    email: string;
    role?: string;
    preferredLanguage?: string;
    heroConfig?: CodecombatApi.HeroConfig;
    birthday?: string;
}
