/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodeCombat } from "@fern-api/codecombat";

export interface CreateUserRequest {
    name: string;
    email: string;
    role?: CodeCombat.UserRole;
    preferredLanguage?: string;
    heroConfig?: CodeCombat.HeroConfig;
    birthday?: string;
}
