/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetClassroomsRequest {
    /**
     * limit the return number of members for each classroom
     */
    retMemberLimit?: number;
}
