/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetUserRequest {
    /**
     * Set to non-empty string to include stats.playTime in response
     */
    includePlayTime?: string;
}
