/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { CodecombatApi } from "@fern-api/codecombat";

export interface GrantUserClassroomAccessRequest {
    /**
     * The document's `_id` or `slug`.
     */
    handle: string;
    body: CodecombatApi.Subscription;
}
