/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LookupUserRequest {
    /**
     * The property to lookup by. May either be `"israel-id"` or `"name"`.
     */
    property: string;
    /**
     * The value to be looked up.
     */
    value: string;
}
