/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ModifyUserRequest {
    /**
     * The document's `_id` or `slug`.
     */
    handle: string;
    name: string;
    birthday?: string;
}
