/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SetAceConfigRequest {
    /**
     * The document's `_id` or `slug`.
     */
    handle: string;
    liveCompletion?: boolean;
    behaviors?: boolean;
    language?: string;
}
