/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateUserRequest {
    /** Set to new name string */
    name: string;
    /** Set the birthday */
    birthday?: string;
}
