/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "../../../..";

export interface UsersShortenLicenseRequest {
    ends: CodeCombat.DatetimeString;
}
