/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as CodeCombat from "../../../..";

export interface UsersCreateRequest {
    name: string;
    email: string;
    /**
     * `"student"` or `"teacher"`. If unset, a home user will be created, unable to join classrooms.
     *
     */
    role?: CodeCombat.UsersCreateRequestRole;
    preferredLanguage?: string;
    heroConfig?: CodeCombat.UsersCreateRequestHeroConfig;
    birthday?: string;
}
