/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const AuthIdentity: core.serialization.ObjectSchema<serializers.AuthIdentity.Raw, CodeCombat.AuthIdentity> =
    core.serialization.object({
        provider: core.serialization.string().optional(),
        id: core.serialization.string().optional(),
    });

export declare namespace AuthIdentity {
    interface Raw {
        provider?: string | null;
        id?: string | null;
    }
}
