/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Course: core.serialization.ObjectSchema<serializers.Course.Raw, CodecombatApi.Course> =
    core.serialization.object({
        id: core.serialization.property(
            "_id",
            core.serialization.lazy(async () => (await import("../../..")).ObjectId).optional()
        ),
        levels: core.serialization.list(core.serialization.unknown()).optional(),
        enrolled: core.serialization
            .list(core.serialization.lazy(async () => (await import("../../..")).ObjectId))
            .optional(),
        instanceId: core.serialization.property(
            "instance_id",
            core.serialization.lazy(async () => (await import("../../..")).ObjectId).optional()
        ),
    });

export declare namespace Course {
    interface Raw {
        _id?: serializers.ObjectId.Raw | null;
        levels?: unknown[] | null;
        enrolled?: serializers.ObjectId.Raw[] | null;
        instance_id?: serializers.ObjectId.Raw | null;
    }
}
