/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const Datetime: core.serialization.Schema<serializers.Datetime.Raw, CodeCombatApi.Datetime> =
    core.serialization.string();

export declare namespace Datetime {
    type Raw = string;
}
