/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const License: core.serialization.ObjectSchema<serializers.License.Raw, CodeCombat.License> =
    core.serialization.object({
        ends: core.serialization.lazy(async () => (await import("../../..")).DatetimeString).optional(),
        active: core.serialization.boolean().optional(),
    });

export declare namespace License {
    interface Raw {
        ends?: serializers.DatetimeString.Raw | null;
        active?: boolean | null;
    }
}
