/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodecombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const OauthIdentity: core.serialization.ObjectSchema<
    serializers.OauthIdentity.Raw,
    CodecombatApi.OauthIdentity
> = core.serialization.object({
    provider: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
});

export declare namespace OauthIdentity {
    interface Raw {
        provider?: string | null;
        id?: string | null;
    }
}
