/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombat } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const ObjectIdString: core.serialization.Schema<serializers.ObjectIdString.Raw, CodeCombat.ObjectIdString> =
    core.serialization.string();

export declare namespace ObjectIdString {
    type Raw = string;
}
