/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { CodeCombatApi } from "@fern-api/codecombat";
import * as core from "../../../../core";

export const UserStats: core.serialization.ObjectSchema<serializers.UserStats.Raw, CodeCombatApi.UserStats> =
    core.serialization.object({
        gamesCompleted: core.serialization.number().optional(),
        playTime: core.serialization.number().optional(),
    });

export declare namespace UserStats {
    interface Raw {
        gamesCompleted?: number | null;
        playTime?: number | null;
    }
}
